<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>AnimatedSwine37</Authors>
        <Description>Interfaces for the Reloaded Localisation Framework mod API</Description>
        <PackageProjectUrl>https://github.com/AnimatedSwine37/Reloaded.Universal.Localisation.Framework</PackageProjectUrl>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/AnimatedSwine37/Reloaded.Universal.Localisation.Framework</RepositoryUrl>
        <RepositoryType>GitHub</RepositoryType>
        <PackageTags>reloaded</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

</Project>
